version: '3.9'

services:
  app:
    image: meselghea/my-backend-infra
    container_name: meselghea-backend-infra-app
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env
    restart: always
