version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: mesel-backend-infra-database
    hostname: database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
  app:
    image: asia-southeast2-docker.pkg.dev/durable-tangent-387511/docker/my-backend-infra
    container_name: meselghea-backend-infra-app
    build: .
    ports:
      - 80:4000
      - 443:4000
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - database
    restart: always

volumes:
  postgres:

service_name:
  environment:
    - DOCKER_DEFAULT_PLATFORM=linux/amd64